modLoader="javafml" #mandatory

loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="MIT"

issueTrackerURL="https://github.com/kyrptonaught/customportalapi/issues" #optional

[[mods]] #mandatory

modId="customportalapi" #mandatory

version="0.0.1-beta1-1.20" #mandatory

displayName="Custom Portal Api [Forge]" #mandatory

displayURL="https://github.com/kyrptonaught/customportalapi" #optional

logoFile="icon.png" #optional

credits="kyrptonaught (main author of the fabric version), Waterpicker (for the forge port) ,Mysticpasta1 (for the forge toml and port to 1.18.2+)" #optional

authors="kyrptonaught, Waterpicker, Mysticpasta1" #optional

description='''
Create portals out of anything!
'''

[[dependencies.customportalapi]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[46,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.customportalapi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20, 1.21)"
    ordering="NONE"
    side="BOTH"